### ISSUE TITLE
Invalid version in datamanager dependency causes game to not boot

### ISSUE THREAD

**Issue by MangoDev1** [IIpho3nix/airplace-comission-mod#1]
The `datamanager-1.0.0.jar` dependency has an invalid version listed in its `fabric.mod.json` (`"version": ""`), causing a parsing error and causing the server to fail to launch. The mod's ID also starts with an `_`, which also causes the game to crash.

Solution: Rebuild `datamanager` with the `"version"` in `fabric.mod.json` to `"1.0.0"`, and set the `"id"` to `datamanager-1_0_0`. I would make a pull request, but I cannot due to the dependency in question being proprietary.

**Comment by IIpho3nix** [comment]
datamanager is not a fabric mod in itself and the depenedncy is included in the jar when its built

i do not quite understand by what you mean by datamanager-1.0.0.jar's fabric.mod.json file as such file does not exist

you can see the source code of datamanager at : https://github.com/IIpho3nix/Data-Manager

**Comment by MangoDev1** [comment]
> i do not quite understand by what you mean by datamanager-1.0.0.jar's fabric.mod.json file as such file does not exist

I think the problem is that a regular `.jar` library is being included as a jar-in-jar Minecraft library, as the mod errors on boot trying to load an invalid (presumeably auto-generated) `fabric.mod.json`.

![Screenshot_20240711_121316](https://github.com/IIpho3nix/airplace-comission-mod/assets/94928669/7337096c-999f-471c-b921-1391cd541952)

**Comment by MangoDev1** [comment]
The current auto-generated `fabric.mod.json` is an invalid mod json, causing the game to crash:
```json
{
  "schemaVersion": 1,
  "id": "_datamanager-1_0_0",
  "version": "",
  "name": "datamanager-1.0.0",
  "custom": {
    "fabric-loom:generated": true
  }
}
```

**Comment by IIpho3nix** [comment]
the fabric.mod.json is generated by fabric itself and the way the dependency is included both valid for mod and non-mod dependencies, have you tried recompiling?

**Comment by MangoDev1** [comment]
yes

**Comment by IIpho3nix** [comment]
are you sure this happens when the mod is compiled as is from the repository? i seen from the screenshot that you modified the version etc. i havent been able to replicate this issue myself

**Comment by MangoDev1** [comment]
> are you sure this happens when the mod is compiled as is from the repository? i seen from the screenshot that you modified the version etc. i havent been able to replicate this issue myself

right off the bat, i get this error after cloning the repo and opening in intellij idea: 
![image](https://github.com/user-attachments/assets/8b6c1396-7eb3-41b0-b2fc-1c0548906833)

**Comment by MangoDev1** [comment]
after adding the missing library, the build succeeds
however, after trying to boot it in a dedicated server, the server errors out on boot
![image](https://github.com/user-attachments/assets/af5f0285-7b07-42e8-abaa-115214fb4fd3)

**Comment by MangoDev1** [comment]
so yes, the mod technically builds, but the built mod is invalid and does not boot

**Comment by MangoDev1** [comment]
and i'm using latest fabric 1.20.1 (0.15.11)

**Comment by MangoDev1** [comment]
it _compiles_ valid, but **_the mod does not run_**

**Comment by MangoDev1** [comment]
got a working version, however it crashes whenever easyplace/airplace is actually used
```log
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-07-11 15:44:53
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: eu/pb4/banhammer/impl/BHUtils
	at me.iipho3nix.antiairplace.BanManager.banPlayer(BanManager.java:12)
	at net.minecraft.class_1747.handler$zza000$anti-air-place$placeBlock(class_1747.java:562)
	at net.minecraft.class_1747.method_7708(class_1747.java)
	at net.minecraft.class_1747.method_7712(class_1747.java:80)
	at net.minecraft.class_1747.method_7884(class_1747.java:50)
	at net.minecraft.class_1799.method_7981(class_1799.java:272)
	at net.minecraft.class_3225.method_14262(class_3225.java:360)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: eu.pb4.banhammer.impl.BHUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.9.8-arch1-1
	Java Version: 17.0.11, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1209785344 bytes (1153 MiB) / 2332033024 bytes (2224 MiB) up to 8384413696 bytes (7996 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU116 [GeForce GTX 1660 SUPER]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 55988.47
	Virtual memory used (MB): 19662.55
	Swap memory total (MB): 40000.00
	Swap memory used (MB): 2.75
	JVM Flags: 0 total; 
	Fabric Mods: 
		anti-air-place: Anti Air Place 1.1.1
			datamanager-1_0_0: datamanager-1.0.0 1.0.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
	Server Running: true
	Player Count: 1 / 20; [class_3222['MangoDev_'/436, l='ServerLevel[world]', x=-170.05, y=68.40, z=-28.32]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by MangoDev1** [comment]
update: it works, but the mod does not _require_ BanHammer, leading to the crash if BanHammer is not in the mod folder

**Comment by MangoDev1** [comment]
fixed in pull request
